### ISSUE TITLE
GetLatestTick (get latest candle)

### ISSUE THREAD

**Issue by frzsombor** [dparlevliet/node.bittrex.api#110]
I just found that in API v2.0 we can also get the last candle only (not just the complete history), which is really useful in my opinion. I think it's definitely worth implementing.

Source:
https://github.com/thebotguys/golang-bittrex-api/wiki/Bittrex-API-Reference-(Unofficial)#getlatesttick

Also, I found that [in the source](https://github.com/dparlevliet/node.bittrex.api/blob/master/node.bittrex.api.js#L336-L407) that every function's name is the same as the api url path, except _getcandles_

So I think it would be good to replace [that](https://github.com/dparlevliet/node.bittrex.api/blob/master/node.bittrex.api.js#L357-L359)
```
    getcandles: function(options, callback) {
      publicApiCall(opts.baseUrlv2 + '/pub/market/GetTicks', callback, options);
    },
```
with
```
    getticks: function(options, callback) {
      publicApiCall(opts.baseUrlv2 + '/pub/market/GetTicks', callback, options);
    },
    getlatesttick: function(options, callback) {
      publicApiCall(opts.baseUrlv2 + '/pub/market/GetLatestTick', callback, options);
    },
```

**Comment by mozhunt** [comment]
Guys, can you help me ? How can i get the previous data of GetLatestTick in Bittrex ? 
Example: 
https://bittrex.com/Api/v2.0/pub/market/GetLatestTick?marketName=BTC-LTC&tickInterval=fiveMin&timestamp=1514734200
write
{"success":true,"message":"","result":[{"O":0.01687427,"H":0.01697220,"L":0.01682000,"C":0.01694900,"V":571.53639338,"T":"2018-01-01T11:35:00","BV":9.68828861}]}

but it's data from 11:35 till 11:40 and it's changes , thats why it's incorrect. 
Correct will be after thes perios closed - in 11:41. 
But in this time GetLatestTick will be show the data since 11:40 till 11:45 . 

If i use GetTicks , i get all 4760 strings of data, but need one previous before the last.
What can i do? What i should use ?
Sorry for my english :)
