### ISSUE TITLE
Immediate or Cancel

### ISSUE THREAD

**Issue by ChadMC** [dparlevliet/node.bittrex.api#17]
This question was asked in the other repository, but was never resolved. Does anyone know how to make a buy/sell with Immediate or Cancel option with the unofficial v2 api? If someone could just give an example of the URL to call it manually, I could implement it myself. Thanks.

**Comment by dparlevliet** [comment]
I don't know how to do it but it should be very easy to work out. I can sort that out later today.

However, If you're building a bot that depends on it you should note that most other exchanges don't have it as an option so keep that in mind if you plan to hook your bot up to other exchanges.

**Comment by gerardo15** [comment]
What i do to buy inmediate, just take the price add 5% and send the request.. it will buy you at the best available price.

**Comment by ChadMC** [comment]
That would be like doing a market buy/sell, which is different than Immediate or Cancel. If it can't purchase the full amount at the price I request, I need it to cancel for the strategy I am implementing. But I have done something similar when I needed a Market buy/sell.

**Comment by dparlevliet** [comment]
I have narrowed down the methods and the parameters needed, however it appears the v2 uses a different system for private api calls which I haven't yet figured out. I'll keep investigating.

**Comment by ChadMC** [comment]
Thanks for looking into it! I'll play around with it as well.

**Comment by dparlevliet** [comment]
Ok, I have updated this release candidate with the working functions that will support IOC and FOK. I have tested it personally and it worked fine, the response was

```json
{ success: true,
  message: '',
  result: 
   { OrderId: '...',
     MarketName: 'BTC-SC',
     MarketCurrency: 'SC',
     BuyOrSell: 'Sell',
     OrderType: 'LIMIT',
     Quantity: 1,
     Rate: 0.044 } }
```

It appears you would have to look up the order by the uuid immediately after to see if it was filled or cancelled because the API doesn't return the result, just the order details.

**Comment by ChadMC** [comment]
Awesome! Great job! Maybe one day they'll return the response directly. I'm closing the issue.

**Comment by dparlevliet** [comment]
Thanks. I'll leave the issue open until I update the package on npmjs. It's late here so I'll do that tomorrow.

Note: Thanks to @llazzaro here https://github.com/ericsomdahl/python-bittrex/issues/35 for tracking down the right endpoint and saving me a bunch of time

**Comment by ChadMC** [comment]
Were you able to get FILL_OR_KILL working in your testing? It looks like the API may just not support it yet. But I just wanted to make sure I wasn't doing something wrong first. I took the example from the README which works fine with IMMEDIATE_OR_CANCEL and replaced the value with FILL_OR_KILL. Anything else I should be doing?

**Comment by dparlevliet** [comment]
Yeah, I don't think it's an enabled option because it's not listed on the website but it is, or was, an option which they mentioned in the blog post when they announced IOC. Not exactly sure if it's removed or just disabled, we probably wont know until we get official documentation or it turns up as an option on the website.
