### ISSUE TITLE
More Hub Events

### ISSUE THREAD

**Issue by wendelmaques** [dparlevliet/node.bittrex.api#23]
Hi guys, correct me if I'm wrong: but, looking at https://bittrex.com/signalr/hubs I can see some interestingly events that I can subscribe (?) to be notified about user balance or order closes?

I'm looking for a way to implement this events, but I'm studying how signalr works, so, someone can take a look to see if is possible to implement this events on node.bittrex.api?

I think this is the same events that notify user on top-right popup when a order is filled. I'm right?

**Comment by dparlevliet** [comment]
Yes, unfortunately the websocket api is still new and right now I believe the only way to receive messages from those channels is by copying a bunch of headers from your browser connection after you login and adding them to your bot manually because Bittrex doesn't yet have a method to authenticate your websocket connection with the api keys.

They do have plans for implementing an official authentication system, but we were told by Bittrex it does not yet exist so hopefully they'll update us when that changes.
