### ISSUE TITLE
ESOCKETTIMEDOUT randomly

### ISSUE THREAD

**Issue by Patafix** [dparlevliet/node.bittrex.api#38]
Hello since yesterday i have a lot of ESOCKETTIMEDOUT error.

I search a lot but cant find answer did they change something to the API ?

Full log here 
[log.txt](https://github.com/dparlevliet/node.bittrex.api/files/1345746/log.txt)

Thx for you're help

**Comment by dparlevliet** [comment]
This is because I added a timeout to the HTTP requests of 15s. You must be hitting it, which I wouldn't have expect. I thought 15s was more than enough time, but I'll make it optional. Other users were complaining of connections not timing out and it was haulting their bots so a timeout was necessary.

**Comment by Patafix** [comment]
Actually i didnt complain i like this feature.
Did you know why bittrex timeout recently ?

**Comment by manu354** [comment]
@dparlevliet where could one lower the time it takes for the timeout? e.g to 5s

**Comment by dparlevliet** [comment]
I can't explain why you would be getting the timeouts more recently. That would be a Bittrex related issue, maybe.

@manu354 yep, I will add that shortly
