### ISSUE TITLE
Is there any official bittrex websocket documentation?

### ISSUE THREAD

**Issue by knap1930** [dparlevliet/node.bittrex.api#49]
This seems to be the only project that supports bittrex web sockets that I can find... did you just reverse engineer their protocol, or am I retarded and can't use Google?

https://bittrex.com/home/api has no mention of web sockets... :(

**Comment by dparlevliet** [comment]
Correct, I reverse engineered it from the website and the original owner of the package integrated it. Unfortunately it's not "officially" supported by Bittrex because it's not yet complete by their standards so we don't have full understanding of what it can do and some functionality isn't available from the API side. You're not insane, it's ok!
