### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by bullet-tooth** [dparlevliet/node.bittrex.api#63]
Hey, 
I'm using vuejs+webpack project and trying to access public API. But when I call the API it gets me an arror:
`Failed to load https://bittrex.com/api/v1.1/public/getmarkets: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

My code snippet is follow:
``` 
const APIKEY = 'KEY'
const APISECRET = 'SECRET'
var bittrex = require('node-bittrex-api')
const HEADERS = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept'
  }
bittrex.options({
    apikey: APIKEY,
    apisecret: APISECRET,
    verbose: true,
    headers: HEADERS
  })

        bittrex.getmarkets(function (data, err) {
          if (err) {
            return console.error(err)
          }
          for (let i in data.result) {
            if (i.IsActive) {
              this.items.push(i)
            }
          }
        })
```
Also I tried to play with/without headers but with no luck.
Please help me to solve this.

**Comment by dparlevliet** [comment]
You have no control over this. This error is chrome denying the request because of headers sent back from the server. They recently enabled Cloudflare again so if you had it working before this is likely the reason it's not working now., Reasons like this are an example of why this project isn't expected or promised to work in the browser, sorry. 

I suggest you just create your own light proxy api that interacts with bittrex via you backend and forwards the response to the front-end. It'll save you a bunch of time and headaches.

Also, you don't need apikeys to access public data.

**Comment by JeffWScott** [comment]
Yeah I would also recommend an API backend.  I like the express react-backend myself.

**Comment by charly37** [comment]
You can also drop a support request to bittrex and ask them to allow CROS. Maybe if enough people ask they would consider it.
