### ISSUE TITLE
Connection aborted?

### ISSUE THREAD

**Issue by gerardo15** [dparlevliet/node.bittrex.api#8]
Hey,

Before you made the fork i had the following code

`   
 websocketsclient.serviceHandlers.disconnected = function (websocket) {
            setImmediate(function () {
                console.log("trying to reconnect");
                websocketsclient.start();
            });
    };
`

now it tells me websocketsclient is undefined and my connection gets aborted and i am not able to reconnect it

**Comment by dparlevliet** [comment]
Yes, the websockets had to change to fix the issues with it caused by changes from Bittrex. Please see the updated documentation and ``examples/`` folder for examples on how to use the new websockets. Additionally, I have already added that functionality to the serviceHandlers by default so you do not need to add it anymore.

I do not know what the "Connection aborted" is specifically. Please run the unit tests and/or the examples in the examples folder and let me know if they work for you or not.
